# Generated by Django 4.0.3 on 2022-10-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0002_rename_name_user_username_user_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('COM', 'Combat'), ('CRA', 'Crafting')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
